# Generated by Django 4.0.4 on 2022-05-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestelldatum', models.DateTimeField(auto_now_add=True)),
                ('bestellsumme', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=200, null=True)),
                ('nachname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preis', models.FloatField()),
                ('kategorie', models.CharField(max_length=200)),
                ('produktbild', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Warenkorb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwischensumme', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zahlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summe', models.FloatField()),
                ('zahlungsart', models.CharField(max_length=100)),
                ('zahlungsdatum', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WarenkorbProdukt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField()),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.produkt')),
                ('warenkorb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.warenkorb')),
            ],
        ),
        migrations.CreateModel(
            name='BestellungProdukt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField()),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.produkt')),
                ('warenkorb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bestellung')),
            ],
        ),
        migrations.AddField(
            model_name='bestellung',
            name='kunde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.kunde'),
        ),
    ]
